default:
  ingestion:
    koboform:
      asset_id: !expr Sys.getenv('KOBO_ASSET_ID')
      username: !expr Sys.getenv('KOBO_USERNAME')
      password: !expr Sys.getenv('KOBO_PASSWORD')
  storage:
    mongodb:
      connection_string: !expr Sys.getenv('MONGODB_CONNECTION_STRING')
      database:
        pipeline:
          name: pipeline
          collection_name:
            raw: raw
            preprocessed: preprocessed
            validated: validated
  validation:
    k_nboats: 3
    k_nfishers: 3
    k_catch: 2.5

production:
  storage:
    mongodb:

local:
  inherits: development
  ingestion:
    koboform:
      asset_id: !expr readLines("auth/kobo-asset-id")
      username: !expr readLines("auth/kobo-username")
      password: !expr readLines("auth/kobo-password")
  storage:
    mongodb:
      connection_string: !expr readLines("auth/mongodb-connection-string")
