default:
  ingestion:
    koboform:
      asset1: !expr Sys.getenv('MALAWI_SSF')
      asset2: !expr Sys.getenv('FISHERIES_ECAS')
      asset3: !expr Sys.getenv('FIELDDATAAPP_2024')
      asset4: !expr Sys.getenv('FIELDDATAAPP_2024A')
      asset5: !expr Sys.getenv('FIELDDATAAPP_2023F')
      username: !expr Sys.getenv('KOBO_USERNAME')
      password: !expr Sys.getenv('KOBO_PASSWORD')
    pds:
      token: !expr Sys.getenv('PDS_TOKEN')
      secret: !expr Sys.getenv('PDS_SECRET')
  storage:
    mongodb:
      connection_string: !expr Sys.getenv('MONGODB_CONNECTION_STRING')
      database:
        pipeline:
          name: pipeline
          collection_name:
            raw: raw
            preprocessed: preprocessed
            validated: validated
        app:
          name: app
          collection_name:
            summary: DataSummaries
    google:
      key: gcs
      options:
        project: peskas
        bucket: kenya-dev
        service_account_key: !expr Sys.getenv('GCP_SA_KEY')
  metadata:
    google_sheets:
      name: metadata-tables
      sheet_id: !expr Sys.getenv("GOOGLE_SHEET_ID")
      tables:
        - devices
  validation:
    k_nboats: 3
    k_nfishers: 3
    k_catch: 2.5
    k_pricekg: 9

production:
  storage:
    mongodb:
      connection_string: !expr Sys.getenv('MONGODB_CONNECTION_STRING')

local:
  inherits: development
  ingestion:
    koboform:
      asset1: !expr readLines("auth/ASSET-malawi-ssf")
      asset2: !expr readLines("auth/ASSET-fisheries-ecas")
      asset3: !expr readLines("auth/ASSET-fielddataapp-2024")
      asset4: !expr readLines("auth/ASSET-fielddataapp-2024A")
      asset5: !expr readLines("auth/ASSET-fielddataapp-2023F")
      username: !expr readLines("auth/kobo-username")
      password: !expr readLines("auth/kobo-password")
    pds:
      token: !expr readLines('auth/pds-token')
      secret: !expr readLines('auth/pds-secret')
  storage:
    mongodb:
      connection_string: !expr readLines("auth/mongodb-connection-string")
    google:
      options:
        service_account_key: !expr readLines("auth/gcp-sa-peskas_ingestion-key.json")
  metadata:
    google_sheets:
      sheet_id: !expr readLines("auth/metadata-sheet-id")
